# Bot token
TOKEN: abalabahaha

# How long in hours from midnight of UTC to start the cycle
OFFSET: 0
# How many times a day the banner should change. If it's too large Discord won't like it so keep it to at least under 24.
INTERVAL_COUNT: 16

# ID of the guild to function in.
GUILD_ID: 0
# Folder directory with all the banners. Can be nested. Only .png files will be used.
FILEPATH: banners/

# ID of the owner. Can reload banners.
OWNER_ID: 0
# Role ID for people who can reload banners.
MAINTAINER_ROLE: 0

# Command to run to reload the banners. Run this after updating the banners in the folder.
RELOAD_CMD: +reloadbanners

# If it can't find the guild or has no permissions, how long until it tries again.
RETRY_INTERVAL: 5

# Channel ID for logging banner changes.
LOG_CHANNEL_ID: 0

# File to record/recall banner progress between restarts. Script requires ability to read/write files in directory. Set to `null` to disable.
BANNER_PROGRESS_RECORD: progress.txt

# Responses for funny "who is the banner", "why is the banner", "how is the banner", etc.
WHO_RESPONSES:
  - me
WHY_RESPONSES:
  - yeah
WHERE_RESPONSES:
  - here
WHEN_RESPONSES:
  - now
HOW_RESPONSES:
  - the banner is doing well
WHAT_RESPONSES:
  - sleeping

# Command to run to eval. Probably don't set this unless to debug.
EVAL_CMD: null